# Publish joint_states from Gazebo.
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

left_arm_joint_traj_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - left_arm_shoulder_pan_joint
    - left_arm_shoulder_lift_joint
    - left_arm_elbow_joint
    - left_arm_wrist_1_joint
    - left_arm_wrist_2_joint
    - left_arm_wrist_3_joint

right_arm_joint_traj_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - right_arm_shoulder_pan_joint
    - right_arm_shoulder_lift_joint
    - right_arm_elbow_joint
    - right_arm_wrist_1_joint
    - right_arm_wrist_2_joint
    - right_arm_wrist_3_joint

gazebo_ros_control:
  pid_gains:
    left_arm_shoulder_pan_joint: {p: 1000.0, i: 0.01, d: 10.0}
    left_arm_shoulder_lift_joint: {p: 1000.0, i: 0.01, d: 10.0}
    left_arm_elbow_joint: {p: 1000.0, i: 0.01, d: 10.0}
    left_arm_wrist_1_joint: {p: 200.0, i: 0.01, d: 2.0}
    left_arm_wrist_2_joint: {p: 200.0, i: 0.01, d: 2.0}
    left_arm_wrist_3_joint: {p: 200.0, i: 0.01, d: 2.0}
    right_arm_shoulder_pan_joint: {p: 1000.0, i: 0.01, d: 10.0}
    right_arm_shoulder_lift_joint: {p: 1000.0, i: 0.01, d: 10.0}
    right_arm_elbow_joint: {p: 1000.0, i: 0.01, d: 10.0}
    right_arm_wrist_1_joint: {p: 200.0, i: 0.01, d: 2.0}
    right_arm_wrist_2_joint: {p: 200.0, i: 0.01, d: 2.0}
    right_arm_wrist_3_joint: {p: 200.0, i: 0.01, d: 2.0}
